name: Test & build

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      api_url: ${{ secrets.API_URL }}
      mapbox_api_key: ${{ secrets.MAPBOX_API_KEY }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create secrets file
        run: |
          cat << EOF > lib/secrets.dart
          const apiUrl = '${{ env.api_url }}';

          const mapBoxApiKey = '${{ env.mapbox_api_key }}';
          EOF
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk